//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public int JobId { get; set; }
        public int CandidateId { get; set; }
        public string CoverLetter { get; set; }
        public Nullable<System.DateTime> AppliedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual JobPost JobPost { get; set; }
    }
}
