//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public JobPost()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int JobId { get; set; }
        public int EmployerId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual User User { get; set; }
    }
}
